.PHONY: setup dev test e2e lint format build

setup:
	npm ci

dev:
	npm run dev -- --hostname localhost

test:
	npm run test

e2e:
	npm run e2e

lint:
	npm run lint

format:
	npm run format

build:
	npm run build
